# PHYSBO Experiment Configuration

# Number of AI-robot cycles
cycles_num: 15

# Number of objectives
objectives_num: 1

# Trial number
trial: 5

# Batch size for proposals
batch_size: 2

# Random seed for initial random selection
re_seed: 111

# Whether to use DPP
use_dpp: false
